### PR TITLE
ENG-405: build project from db resources

### PR DESCRIPTION
**Pull request by efiShtain**
```bash
ak projects set-resources <project_name or id> -p <path to directory or file>

ak projects download-resources <project_name or id> -o <output directory path>
```

set-resources is atomic and replaces all resources currently stored on AK server for a project (not incremental/sync capabilities)

User has to run set-resources every time he cares to update the source code of the project and deploy a new version

superceded by #10

### CODE REVIEW

**Comment by itayd** [comment]
does this means that from the moment this is in everybody will have to update the resources to build?

**Comment by efiShtain** [comment]
> does this means that from the moment this is in everybody will have to update the resources to build?

you are correct

I've showed @RonenMars the change, waiting for him to update the extension

do you want to do it in another way?

**Comment by itayd** [comment]
i wonder if there is a way to allow both
like two source providers, one local and one program store. we should discuss

**Comment by efiShtain** [comment]
There is, once we have the source provider abstraction, we can add a local source provider which will have direct access to the files

Part of the design in case we want to support it, but currently without source providers it makes the code harder for no good reason

But let's discuss

BTW, this change is a requirement for cloud usage

**Review by daabr — COMMENTED** [review]
I didn't review this PR yet due to the US holiday - will do tomorrow morning.

Anyway, can you add to the PR description a comment about how this will look like from the user's perspective? i.e. if/how it will change the current interaction with VSCode and/or the CLI?

**Comment by efiShtain** [comment]
> There is, once we have the source provider abstraction, we can add a local source provider which will have direct access to the files
> 
> Part of the design in case we want to support it, but currently without source providers it makes the code harder for no good reason
> 
> But let's discuss
> 
> BTW, this change is a requirement for cloud usage

added to the PR description

**Review by daabr — APPROVED** [review]

**Pull request closed without merging**
