### PR TITLE
feat(python): next_event support several subscriptions.

### PR DESCRIPTION
**Pull request by tebeka**
Fixes ENG-1209

### CODE REVIEW

**Comment by daabr** [comment]
Can you explain how this change will be used by users? Not this function itself, which is a dummy for local testing, but the API that it interacts with - what's the difference between `sub_id` and `sub_ids`? Or is this just a halfway to something else?

**Comment by tebeka** [comment]
> Can you explain how this change will be used by users? Not this function itself, which is a dummy for local testing, but the API that it interacts with - what's the difference between `sub_id` and `sub_ids`? Or is this just a halfway to something else?

The user can either do `ak.next_event('sig1')` or `ak.next_event('sig1', 'sig2')`
The way Python sends the call to `ak` is to pack all arguments so there's no need to change the code `pythonrt.go`.
`sub_ids` are the rest of IDs, I want to force the user to specify at least one signal.

**Comment by daabr** [comment]
> The user can either do `ak.next_event('sig1')` or `ak.next_event('sig1', 'sig2')` The way Python sends the call to `ak` is to pack all arguments so there's no need to change the code `pythonrt.go`. `sub_ids` are the rest of IDs, I want to force the user to specify at least one signal.

In that case, maybe call them `required_sub_id` and `optional_sub_ids` as a form of self-documentation? Or add per-arg descriptions in the docstring?

It's not a blocker, so I'm approving, but given that it's visible to users I expect it to be understandable by any user without our help.

**Review by daabr — APPROVED** [review]

**Comment by itayd** [comment]
@daabr - this is how it works in starlark as well.

**Pull request closed without merging**
