### PR TITLE
chore: kill unused db integration code

### PR DESCRIPTION
**Pull request by itayd**

### CODE REVIEW

**Review by efiShtain — APPROVED** [review]

**Comment by ig-ra** [comment]
@itayd 
do we need integration in schema?
there are at least 3 files that contain more remainings of integration DB code

**Review by ig-ra — CHANGES_REQUESTED** [review]
db schema?

**Review by efiShtain — CHANGES_REQUESTED** [review]
please remove the integration model

**Comment by itayd** [comment]
removed integration model.

**Review by ig-ra — APPROVED** [review]

**Pull request merged**
