### PR TITLE
feat(env)!: non-optional project

### PR DESCRIPTION
**Pull request by ig-ra**
disallowing project to be nil in Env

BREAKING CHANGE: DBs with standalone ENVs (not connected to any project) cannot be migrated and should be reconnected to some existing project or deleted

### CODE REVIEW

**Review by efiShtain — COMMENTED** [review]
Did you check what happens on a database which has null env?
Migration would probably fail
What is the proposed solution for that?

**Comment by ig-ra** [comment]
> Did you check what happens on a database which has null env? Migration would probably fail What is the proposed solution for that?

you mean default env? Default env is created while the project creation.
But there could be some old db with standalone envs. I think we should declare this change as a breaking one

**Review by efiShtain — APPROVED** [review]
Approve
note this is a breaking change

**Comment by ig-ra** [comment]
in create env CMD it's already defined as required flag

**Comment by itayd** [comment]
we currently don't have "dangling envs", but we might in the future where their parents is either an org or a user.

**Pull request merged**
