### PR TITLE
fix(python): SDK docs build failing

### PR DESCRIPTION
**Pull request by tebeka**

### CODE REVIEW

**Comment by efiShtain** [comment]
you should probably add a workflow to verify that the generated code matches the current code and fail otherwise

**Comment by tebeka** [comment]
> you should probably add a workflow to verify that the generated code matches the current code and fail otherwise

Done

**Review by daabr — APPROVED** [review]

**Review by daabr — COMMENTED** [review]
Don't we need to update the SDK version number in `py-sdk/docs/conf.py` too?

**Comment by tebeka** [comment]
> Don't we need to update the SDK version number in `py-sdk/docs/conf.py` too?

Good idea, added code to read it from `pyproject.toml`

**Pull request merged**
