### PR TITLE
feat(ENG-1320): embed web platform in backend

### PR DESCRIPTION
**Pull request by itayd**
- served on port 9982
- enabled only for dev by default

### CODE REVIEW

**Comment by efiShtain** [comment]
I think we should at least have the UI version displayed somewhere, just to make sure we understand it

fix the static analysis 

other than this I'm fine with it for now

**Review by efiShtain — APPROVED** [review]
see my comments

**Review by daabr — CHANGES_REQUESTED** [review]
Let's discuss this in detail offline (once I feel better, hopefully later today)

**Comment by itayd** [comment]
logged the version

**Pull request merged**
