### PR TITLE
python: Temporary way to install packages

### PR DESCRIPTION
**Pull request by tebeka**
Allow users to install packages from workflow code. This is a workaround until we have a way to create custom Python environments per workflow.

See ENG-1219

### CODE REVIEW

**Comment by tebeka** [comment]
@haimzlato This add a way the user can write in the workflow code something like:

```from autokitteh import packages

packages.install(['numpy', 'pandas'])
```

And it'll be installed on the worker. Second call to `install` on the worker will do nothing.
Thoughts?

**Review by daabr — APPROVED** [review]
On one hand, this is mitigating the issue of users not being able to use their preferred packages quickly and easily - which is great!

On the other hand, I'm worried about the indirect implication of lack of protection against disk writing and shell execution - we have to use strict jailing before we make AK more public.

**Comment by itayd** [comment]
interesting, but when should it be executed? in global scope?

**Comment by tebeka** [comment]
> interesting, but when should it be executed? in global scope?

Yes, users will write at top of file
```python
from autokitteh import packages
packages.install(['numpy', 'matplotlib'])
```

I wonder if the API will be better with *args
```python
packages.install('numpy', 'matplotlib')
```

**Pull request merged**
